"interface:credits:project_lead" = "Руководитель Проекта"
"interface:credits:scripting" = "Скрипты"
"interface:credits:quest_writing" = "Написание Квестов"
"interface:credits:artwork" = "Графика"
"interface:credits:music" = "Звук"
"interface:credits:engine" = "Разработчики Движка"
"interface:credits:translation" = "Перевод"
"interface:credits:testing" = "Тестирование"
"interface:credits:build14" = "Сборка № 14"
