[storyline.free_play]
dir = "FreePlay"

[storyline.free_play.start]
location = "Tutorial_Deck"
port = "QC_port"
model = "47_JRMMSub"
first_name = "Julian"
last_name = "McAllister"
nation = "england"
player_type = "rebel"
difficulty = "seadog"
pirate_flag = 5
personal_flag = 30
ship = "BrigRoyal"
ship_name = "Defiance"

editable = [
    "location",
    "port",
    "model",
    "first_name",
    "last_name",
    "nation",
    "player_type",
    "ship",
    "ship_name",
    "nation",
    "personal_flag",
    "pirate_flag",
]

[storyline.free_play.start.date]
hour = 13
min = 20
sec = 33
day = 14
month = 5
year = 1682

[storyline.free_play.variables]
CHANGING_RELATIONS = 1
ISLA_DE_MUERTE = 0
