"interface:credits:project_lead" = "Project lead"
"interface:credits:scripting" = "Scripting"
"interface:credits:quest_writing" = "Questwriting"
"interface:credits:artwork" = "Art"
"interface:credits:music" = "Music"
"interface:credits:engine" = "Engine Development"
"interface:credits:translation" = "Translation"
"interface:credits:testing" = "Testing"
"interface:credits:build14" = "Build 14"
